### ISSUE TITLE
As a searcher / lister, I want to open my profile page and persist and edit personal information about myself into the system, so other parties can have an impression of who I am.

### ISSUE THREAD

**Issue by rafaaaaaaa** [sopra-fs23-group-30/sopra-fs23-group-30-server#50]
**Acceptance Criteria**
- When clicking on “My Profile” in the navbar, my profile page appears.
- I can upload or edit a picture of myself when clicking on the “Change photo” button.
- When clicking the “Delete” button the picture gets deleted, and a placeholder photo
gets displayed.
- By clicking on the according text field, I can add information about the following
topics
o age 
o gender
o description of personality in the “Bio”
o education and the duration in the “Education” text field (multi-add)
o experience and the duration in the “Experience” text field (multi-add)
o description of what I’m looking for in future flatmates in the “I am looking
for”.
- As soon as I start writing in one of the sections listed above, a “Save” and “Cancel”
button appears, when clicking “Save” the data gets persisted and “Cancel” reverted
again

**Development Tasks**
- [x] sopra-fs23-group-30/sopra-fs23-group-30-client#12
- [x] sopra-fs23-group-30/sopra-fs23-group-30-client#29
- [x] sopra-fs23-group-30/sopra-fs23-group-30-client#27
- [x] sopra-fs23-group-30/sopra-fs23-group-30-client#10
- [x] sopra-fs23-group-30/sopra-fs23-group-30-client#25
- [x] sopra-fs23-group-30/sopra-fs23-group-30-server#56
- [x] sopra-fs23-group-30/sopra-fs23-group-30-client#31
