### ISSUE TITLE
As a lister, I want to have an overview of the applicants to my listings, so I can review their profile and potentially accept the best fitting applicant.

### ISSUE THREAD

**Issue by nyc6** [sopra-fs23-group-30/sopra-fs23-group-30-server#75]
**Acceptance Criteria:**
• By expanding an entry on a listing item under “My Listings”, I can see a list of applicants for each applicant thew following will be displayed:
o profile picture
o the name
o the application dates. o “See profile” button.
• By clicking on the “see profile” button, I get directed to the profile page of a searcher.
• For each applicant, I can either reject them or accept them.

**Development Tasks**

- [x] sopra-fs23-group-30/sopra-fs23-group-30-server#76
- [x] sopra-fs23-group-30/sopra-fs23-group-30-client#19
- [x] sopra-fs23-group-30/sopra-fs23-group-30-client#26
