### ISSUE TITLE
As a Lister / Searcher I want to have a nicely styled web page to be able to have a good user experience

### ISSUE THREAD

**Issue by ThePunisher77777** [sopra-fs23-group-30/sopra-fs23-group-30-server#87]
**Dev tasks**

- [x] sopra-fs23-group-30/sopra-fs23-group-30-client#34
- [x] sopra-fs23-group-30/sopra-fs23-group-30-client#35
- [x] sopra-fs23-group-30/sopra-fs23-group-30-client#36
- [x] sopra-fs23-group-30/sopra-fs23-group-30-client#37
- [x] sopra-fs23-group-30/sopra-fs23-group-30-client#38
- [x] sopra-fs23-group-30/sopra-fs23-group-30-client#39
