### ISSUE TITLE
As a Lister / Searcher, I want to user the applications core functionality without encountering any UI or logical bugs.

### ISSUE THREAD

**Issue by rafaaaaaaa** [sopra-fs23-group-30/sopra-fs23-group-30-server#95]
**Dev Tasks**

- [x] sopra-fs23-group-30/sopra-fs23-group-30-client#40

- [x] sopra-fs23-group-30/sopra-fs23-group-30-server#97
- [x] sopra-fs23-group-30/sopra-fs23-group-30-client#41
- [x] sopra-fs23-group-30/sopra-fs23-group-30-server#107
- [x] sopra-fs23-group-30/sopra-fs23-group-30-client#46
- [x] sopra-fs23-group-30/sopra-fs23-group-30-server#101
- [x] sopra-fs23-group-30/sopra-fs23-group-30-server#102
- [x] sopra-fs23-group-30/sopra-fs23-group-30-server#103
- [x] sopra-fs23-group-30/sopra-fs23-group-30-client#43
- [x] sopra-fs23-group-30/sopra-fs23-group-30-client#44
- [x] sopra-fs23-group-30/sopra-fs23-group-30-client#45
